### ISSUE TITLE
Plugin not working with Wp multisite + WPML + Polylang

### ISSUE THREAD

**Issue by avinashcohaesus** [polylang/wpml-to-polylang#1]
I have setup a WordPress multisite environment with WPML for 4 languages (English default) and Polylang (purchases) with latest version.

I import the WPML articles in Polylang with your plugin successfully. But when I check the admin, translations are not related to each other. Means each translation work as an individual article.
For example: In admin, there are 4 homepages and each home page work as an individual. When go to setting> reading and set Home page as landing page then an error message is showing that I need to translate the page first whereas page is already translated in all language. Seems translated pages are not related to each other.

I am using below versions of each one: WP: Latest - 4.7.5 WPML: 3.5.3.1 Polylang: latest version

Anyone please look into this and help me.

**Comment by avinashcohaesus** [comment]
I have setup a WordPress multisite environment with WPML for 4 languages (English default) and Polylang (purchases) with latest version.

I import the WPML articles in Polylang with your plugin successfully. But when I check the admin, translations are not related to each other. Means each translation work as an individual article.
For example: In admin, there are 4 homepages and each home page work as an individual. When go to setting> reading and set Home page as landing page then an error message is showing that I need to translate the page first whereas page is already translated in all language. Seems translated pages are not related to each other.

I am using below versions of each one: WP: Latest - 4.7.5  WPML: 3.5.3.1 Polylang: latest version

Anyone please look into this and help me.

**Comment by Chouby** [comment]
Sorry for the late answer. We just tested the import with the latest versions of all plugins on a multisite and the pages are correctly linked together. I guess that your issue is not related to multisite. Do you remember if it was a big sites with thousands of posts?
