### ISSUE TITLE
After migrating the flags are missing in the language table

### ISSUE THREAD

**Issue by Chrystll** [polylang/wpml-to-polylang#3]
## Plugins activated
WPML to Polylang 0.2.5
Polylang 2.6
WPML Multilingual CMS 4.2.7.1
WPML String Translation 2.10.5.1
WPML Media 2.5.2

## Issue description
After migrating the flags are missing in the language table, see:

![screenshot-localhost-2019 06 26-16-18-07](https://user-images.githubusercontent.com/19824724/60187532-06b5b500-982e-11e9-9aeb-d2cabd6aed75.png)

**Comment by Chouby** [comment]
This bug is introduced by Polylang 2.6.

**Comment by Chrystll** [comment]
I just retested and you fixed the issue. Thank you.
