### ISSUE TITLE
After migrating the "Front page label" is missing for the secondary language

### ISSUE THREAD

**Issue by Chrystll** [polylang/wpml-to-polylang#4]
## Plugins activated
WPML to Polylang 0.2.5
Polylang 2.6
WPML Multilingual CMS 4.2.7.1
WPML String Translation 2.10.5.1
WPML Media 2.5.2

## Issue description
After migrating the "Front page label" is missing for the secondary language, see:

![screenshot-localhost-2019 06 26-16-57-39](https://user-images.githubusercontent.com/19824724/60190801-8b570200-9833-11e9-816c-9f5f7059c7dc.png)

**Comment by Chouby** [comment]
This bug is due to the pll_languages_list transient being filled with empty values for the page_on_front and page_for_posts PLL_Language properties.

**Comment by Chrystll** [comment]
I just retested and you fixed the issue. Thank you.
